'''
  Game Features
'''

# SCREEN
SCREEN_WIDTH = SCREEN_HEIGHT = 640
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# CELLS
CELLS_PER_ROW = 16
CELL_HEIGHT = CELL_WIDTH = SCREEN_WIDTH // CELLS_PER_ROW
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)

# COLORS
BLACK = 0x000000
WHITE = 0xF1F1F1

RED   = 0xFF0000
GREEN = 0x4A8F5D
BLUE  = 0x0000FF

LIGHT_GREEN = 0x7BD4B4

# SNAKE
SNAKE_BODY_COLOR  = GREEN
APPLE_COLOR = RED

SNAKE_START_CELL = [[7,3], [7,2]]

START_VELOCITY = 0.1

# BACKGROUND
BACKGRAOUND_COLOR = LIGHT_GREEN